name: Renovate
on: workflow_dispatch
# jobs:
#   renovate:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2.0.0
#       - name: List
#         run: ls -la
#       - name: Self-hosted Renovate
#         uses: renovatebot/github-action@v32.118.0
#         with:
#           configurationFile: example/renovate-config.js
#           token: ${{ secrets.RENOVATE_TOKEN }}
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: example/renovate-config.js
          token: 'x-access-token:${{ steps.get_token.outputs.app_token }}'